language: r
warnings_are_errors: true

cache: packages

sudo: required

r_binary_packages:
  - ridge

r_github_packages:
  - jimhester/covr
  - SteffenMoritz/imputeR

after_success:
  - Rscript -e 'library(covr);codecov()'