language: r
warnings_are_errors: true

cache: packages

sudo: required

addons:
  apt:
    packages: libgsl0-dev

r_github_packages:
  - jimhester/covr
  - SteffenMoritz/imputeR

after_success:
  - Rscript -e 'library(covr);codecov()'
