language: r
warnings_are_errors: true

cache: packages

sudo: required

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_: false

r_github_packages:
  - jimhester/covr
  - SteffenMoritz/imputeR

after_success:
  - Rscript -e 'library(covr);codecov()'